// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'shared/entities/place_entity.dart';
import 'shared/entities/room_entity.dart';
import 'shared/entities/storage_node_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7870874759693489884),
    name: 'PlaceEntity',
    lastPropertyId: const obx_int.IdUid(9, 8814085795202451710),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 195312368255579858),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4358933961560565034),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5335928931233296268),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3971638116165089961),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6009768700468669979),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1552754926172621671),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7926813910379582183),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5622064714565965224),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8814085795202451710),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8802091182850230581),
    name: 'RoomEntity',
    lastPropertyId: const obx_int.IdUid(9, 8260765816452633537),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2083116115011136486),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7443343198282602900),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1565452542082270617),
        name: 'placeUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7235398777975400842),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5223144287141907694),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4476334529508645945),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3835562554096960023),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5682936595815019489),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8260765816452633537),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5525750899245441717),
    name: 'StorageNodeEntity',
    lastPropertyId: const obx_int.IdUid(18, 3936875561199344098),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3060723912896425799),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5317297573534402957),
        name: 'uuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2684235829347301413),
        name: 'roomUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6507539583636627132),
        name: 'parentUuid',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4117940187178923227),
        name: 'nodeType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6887480387733724489),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8231019296709969052),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3322877606899008310),
        name: 'photoPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2803445941022159092),
        name: 'tags',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2501125355354166416),
        name: 'isImportant',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8564275879526417356),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 8061842724460789209),
        name: 'syncStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3024508705270062766),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6512685287111474719),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 1471165333404250438),
        name: 'viewedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 5374589180224491296),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 7045158865574486976),
        name: 'expiryDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3936875561199344098),
        name: 'trackExpiry',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5525750899245441717),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [7954985803738855653],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6940150155732419772,
      3595684663088714071,
      1532904614690716340,
      7317130013234515172,
      2038007066104165304,
      942364401451154438,
      5095826458160907127,
      655775861612599018,
      8983622826120384276,
      4416566148229295976,
      6775024471717734931,
      7063695872014792823,
      7949199081335155200,
      7940448765401810234,
      7867257424500725406,
      9046119656525438401,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PlaceEntity: obx_int.EntityDefinition<PlaceEntity>(
      model: _entities[0],
      toOneRelations: (PlaceEntity object) => [],
      toManyRelations: (PlaceEntity object) => {},
      getId: (PlaceEntity object) => object.id,
      setId: (PlaceEntity object, int id) {
        object.id = id;
      },
      objectToFB: (PlaceEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final nameOffset = fbb.writeString(object.name);
        final typeOffset = fbb.writeString(object.type);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, typeOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addBool(5, object.isArchived);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.sortOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = PlaceEntity(
          uuid: uuidParam,
          name: nameParam,
          type: typeParam,
          description: descriptionParam,
          isArchived: isArchivedParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          sortOrder: sortOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    RoomEntity: obx_int.EntityDefinition<RoomEntity>(
      model: _entities[1],
      toOneRelations: (RoomEntity object) => [],
      toManyRelations: (RoomEntity object) => {},
      getId: (RoomEntity object) => object.id,
      setId: (RoomEntity object, int id) {
        object.id = id;
      },
      objectToFB: (RoomEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final placeUuidOffset = fbb.writeString(object.placeUuid);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, placeUuidOffset);
        fbb.addOffset(3, nameOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addBool(5, object.isArchived);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.sortOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final placeUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final object = RoomEntity(
          uuid: uuidParam,
          placeUuid: placeUuidParam,
          name: nameParam,
          description: descriptionParam,
          isArchived: isArchivedParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          sortOrder: sortOrderParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    StorageNodeEntity: obx_int.EntityDefinition<StorageNodeEntity>(
      model: _entities[2],
      toOneRelations: (StorageNodeEntity object) => [],
      toManyRelations: (StorageNodeEntity object) => {},
      getId: (StorageNodeEntity object) => object.id,
      setId: (StorageNodeEntity object, int id) {
        object.id = id;
      },
      objectToFB: (StorageNodeEntity object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final roomUuidOffset = fbb.writeString(object.roomUuid);
        final parentUuidOffset = object.parentUuid == null
            ? null
            : fbb.writeString(object.parentUuid!);
        final nodeTypeOffset = fbb.writeString(object.nodeType);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final photoPathOffset = object.photoPath == null
            ? null
            : fbb.writeString(object.photoPath!);
        final tagsOffset = object.tags == null
            ? null
            : fbb.writeString(object.tags!);
        final syncStatusOffset = fbb.writeString(object.syncStatus);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, roomUuidOffset);
        fbb.addOffset(3, parentUuidOffset);
        fbb.addOffset(4, nodeTypeOffset);
        fbb.addOffset(5, nameOffset);
        fbb.addOffset(6, descriptionOffset);
        fbb.addOffset(7, photoPathOffset);
        fbb.addOffset(8, tagsOffset);
        fbb.addBool(9, object.isImportant);
        fbb.addBool(10, object.isArchived);
        fbb.addOffset(11, syncStatusOffset);
        fbb.addInt64(12, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(13, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(14, object.viewedAt?.millisecondsSinceEpoch);
        fbb.addInt64(15, object.sortOrder);
        fbb.addInt64(16, object.expiryDate?.millisecondsSinceEpoch);
        fbb.addBool(17, object.trackExpiry);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final viewedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final expiryDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final roomUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final parentUuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final nodeTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final photoPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final tagsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final isImportantParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          24,
          false,
        );
        final syncStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0),
        );
        final viewedAtParam = viewedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(viewedAtValue);
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final expiryDateParam = expiryDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(expiryDateValue);
        final trackExpiryParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          38,
          false,
        );
        final object = StorageNodeEntity(
          uuid: uuidParam,
          roomUuid: roomUuidParam,
          parentUuid: parentUuidParam,
          nodeType: nodeTypeParam,
          name: nameParam,
          description: descriptionParam,
          photoPath: photoPathParam,
          tags: tagsParam,
          isImportant: isImportantParam,
          isArchived: isArchivedParam,
          syncStatus: syncStatusParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          viewedAt: viewedAtParam,
          sortOrder: sortOrderParam,
          expiryDate: expiryDateParam,
          trackExpiry: trackExpiryParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PlaceEntity] entity fields to define ObjectBox queries.
class PlaceEntity_ {
  /// See [PlaceEntity.id].
  static final id = obx.QueryIntegerProperty<PlaceEntity>(
    _entities[0].properties[0],
  );

  /// See [PlaceEntity.uuid].
  static final uuid = obx.QueryStringProperty<PlaceEntity>(
    _entities[0].properties[1],
  );

  /// See [PlaceEntity.name].
  static final name = obx.QueryStringProperty<PlaceEntity>(
    _entities[0].properties[2],
  );

  /// See [PlaceEntity.type].
  static final type = obx.QueryStringProperty<PlaceEntity>(
    _entities[0].properties[3],
  );

  /// See [PlaceEntity.description].
  static final description = obx.QueryStringProperty<PlaceEntity>(
    _entities[0].properties[4],
  );

  /// See [PlaceEntity.isArchived].
  static final isArchived = obx.QueryBooleanProperty<PlaceEntity>(
    _entities[0].properties[5],
  );

  /// See [PlaceEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<PlaceEntity>(
    _entities[0].properties[6],
  );

  /// See [PlaceEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PlaceEntity>(
    _entities[0].properties[7],
  );

  /// See [PlaceEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<PlaceEntity>(
    _entities[0].properties[8],
  );
}

/// [RoomEntity] entity fields to define ObjectBox queries.
class RoomEntity_ {
  /// See [RoomEntity.id].
  static final id = obx.QueryIntegerProperty<RoomEntity>(
    _entities[1].properties[0],
  );

  /// See [RoomEntity.uuid].
  static final uuid = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[1],
  );

  /// See [RoomEntity.placeUuid].
  static final placeUuid = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[2],
  );

  /// See [RoomEntity.name].
  static final name = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[3],
  );

  /// See [RoomEntity.description].
  static final description = obx.QueryStringProperty<RoomEntity>(
    _entities[1].properties[4],
  );

  /// See [RoomEntity.isArchived].
  static final isArchived = obx.QueryBooleanProperty<RoomEntity>(
    _entities[1].properties[5],
  );

  /// See [RoomEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<RoomEntity>(
    _entities[1].properties[6],
  );

  /// See [RoomEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<RoomEntity>(
    _entities[1].properties[7],
  );

  /// See [RoomEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<RoomEntity>(
    _entities[1].properties[8],
  );
}

/// [StorageNodeEntity] entity fields to define ObjectBox queries.
class StorageNodeEntity_ {
  /// See [StorageNodeEntity.id].
  static final id = obx.QueryIntegerProperty<StorageNodeEntity>(
    _entities[2].properties[0],
  );

  /// See [StorageNodeEntity.uuid].
  static final uuid = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[1],
  );

  /// See [StorageNodeEntity.roomUuid].
  static final roomUuid = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[2],
  );

  /// See [StorageNodeEntity.parentUuid].
  static final parentUuid = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[3],
  );

  /// See [StorageNodeEntity.nodeType].
  static final nodeType = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[4],
  );

  /// See [StorageNodeEntity.name].
  static final name = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[5],
  );

  /// See [StorageNodeEntity.description].
  static final description = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[6],
  );

  /// See [StorageNodeEntity.photoPath].
  static final photoPath = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[7],
  );

  /// See [StorageNodeEntity.tags].
  static final tags = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[8],
  );

  /// See [StorageNodeEntity.isImportant].
  static final isImportant = obx.QueryBooleanProperty<StorageNodeEntity>(
    _entities[2].properties[9],
  );

  /// See [StorageNodeEntity.isArchived].
  static final isArchived = obx.QueryBooleanProperty<StorageNodeEntity>(
    _entities[2].properties[10],
  );

  /// See [StorageNodeEntity.syncStatus].
  static final syncStatus = obx.QueryStringProperty<StorageNodeEntity>(
    _entities[2].properties[11],
  );

  /// See [StorageNodeEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<StorageNodeEntity>(
    _entities[2].properties[12],
  );

  /// See [StorageNodeEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<StorageNodeEntity>(
    _entities[2].properties[13],
  );

  /// See [StorageNodeEntity.viewedAt].
  static final viewedAt = obx.QueryDateProperty<StorageNodeEntity>(
    _entities[2].properties[14],
  );

  /// See [StorageNodeEntity.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<StorageNodeEntity>(
    _entities[2].properties[15],
  );

  /// See [StorageNodeEntity.expiryDate].
  static final expiryDate = obx.QueryDateProperty<StorageNodeEntity>(
    _entities[2].properties[16],
  );

  /// See [StorageNodeEntity.trackExpiry].
  static final trackExpiry = obx.QueryBooleanProperty<StorageNodeEntity>(
    _entities[2].properties[17],
  );
}
